version: '3.7'

services:
  tubearchivist:
    image: bbilly1/tubearchivist:v0.3.0
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.tube.rule: "Host(`tube.apetre.sc`)"
        traefik.http.routers.tube.tls.certResolver: "r53resolver"
        traefik.http.routers.tube.tls.domains[0].main: "apetre.sc"
        traefik.http.routers.tube.tls.domains[0].sans: "*.apetre.sc"
        traefik.http.services.tube.loadbalancer.server.port: 8000
        traefik.docker.network: proxy
      placement:
        constraints:
          - node.labels.zpool == tank2
    networks:
      - default
      - proxy
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - TA_HOST=tube.apetre.sc
      - TA_USERNAME=apetresc
      - TA_PASSWORD=abc
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - ELASTIC_PASSWORD=verysecret
      - TZ=America/Toronto
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson:2.4.2
    deploy:
      placement:
        constraints:
          - node.labels.zpool == tank2
    volumes:
      - redis:/data
    networks:
      - default
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es:8.5.1
    deploy:
      placement:
        constraints:
          - node.labels.zpool == tank2
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=verysecret"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - default

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.130,soft,nolock
      device: ":/srv/nfs/tank1/media/video/YouTube"
  cache:
    driver: zfs
  redis:
    driver: zfs
  es:
    driver: zfs

networks:
  default:
  proxy:
    external: true

