---
nfs_network: "192.168.1.0/24"
nfs_exports:
  - /srv/nfs {{ nfs_network }}(rw,async,no_subtree_check,crossmnt,fsid=0)
  - /srv/nfs/freezer {{ nfs_network }}(rw,async,no_subtree_check,no_root_squash,fsid=1)
  - /srv/nfs/freezer-crypt {{ nfs_network }}(rw,async,no_subtree_check,no_root_squash,fsid=1)
