---
version: '3.7'

services:
  authelia:
    image: authelia/authelia
    volumes:
      - config:/config
    networks:
      - proxy
      - default
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.authelia.rule: "Host(`auth.apetre.sc`)"
        traefik.http.routers.authelia.entrypoints: "https"
        traefik.http.routers.authelia.tls: "true"
        traefik.http.routers.authelia.tls.certResolver: "r53resolver"
        traefik.http.routers.authelia.tls.domains[0].main: "apetre.sc"
        traefik.http.routers.authelia.tls.domains[0].sans: "*.apetre.sc"
        traefik.http.services.authelia.loadbalancer.server.port: 9091
        traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:9091/api/verify?rd=https://auth.apetre.sc"
        traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
        traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
        traefik.docker.network: "proxy"
    healthcheck:
      disable: true
    configs:
      - source: config_20210622
        target: /config/configuration.yml
      - source: users_database
        target: /config/users_database.yml
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - apetresc_smtp_password
    environment:
      - TZ=America/Toronto
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/apetresc_smtp_password

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    networks:
      - default
    environment:
      - TZ=America/Toronto

  secure:
    image: traefik/whoami
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.secure.rule: "Host(`secure.apetre.sc`)"
        traefik.http.routers.secure.tls.certResolver: "r53resolver"
        traefik.http.routers.secure.tls.domains[0].main: "apetre.sc"
        traefik.http.routers.secure.tls.domains[0].sans: "*.apetre.sc"
        traefik.http.services.secure.loadbalancer.server.port: 80
        traefik.http.routers.secure.middlewares: "authelia@docker"
        traefik.docker.network: proxy

  public:
    image: traefik/whoami
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.public.rule: "Host(`public.apetre.sc`)"
        traefik.http.routers.public.tls.certResolver: "r53resolver"
        traefik.http.routers.public.tls.domains[0].main: "apetre.sc"
        traefik.http.routers.public.tls.domains[0].sans: "*.apetre.sc"
        traefik.http.services.public.loadbalancer.server.port: 80
        traefik.http.routers.public.middlewares: "authelia@docker"
        traefik.docker.network: proxy


networks:
  default:
  proxy:
    external: true

volumes:
  config:
    driver: zfs
  redis:
    driver: zfs

configs:
  config_20210622:
    file: ./config/configuration.yml
  users_database:
    file: ./config/users_database.yml

secrets:
  authelia_jwt_secret:
    external: true
  authelia_session_secret:
    external: true
  #authelia_redis_password:
    #external: true
  apetresc_smtp_password:
    external: true
