#!/bin/bash -ex

export CALIBRE_LIBRARY=/books

export BOOK_ID="$1"
export COVER_URL="$2"

curl "$COVER_URL" > /tmp/cover.jpg
calibredb --with-library=$CALIBRE_LIBRARY set_metadata -f cover:/tmp/cover.jpg $BOOK_ID

