#!/bin/bash -ex

CALIBRE_LIBRARY=/books

BOOK_ID="$1"
COVER_PATH="$2"

if [[ COVER_PATH == http* ]]; then
  curl "$COVER_PATH" > /tmp/cover.jpg
  COVER_PATH=/tmp/cover.jpg
fi

calibredb --with-library=$CALIBRE_LIBRARY set_metadata -f cover:$COVER_PATH $BOOK_ID

