---
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
default_redirection_url: https://public.apetre.sc
totp:
  issuer: authelia.com

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldap://openldap
    start_tls: false
    tls:
      server_name: openldap
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: dc=apetre,dc=sc
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: cn
    user: cn=admin,dc=apetre,dc=sc


access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: public.apetre.sc
      policy: bypass
    - domain: secure.apetre.sc
      policy: two_factor
    - domain: jackett.apetre.sc
      policy: two_factor
    - domain: homebridge.apetre.sc
      policy: two_factor

session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: apetre.sc  # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: adrian@apetre.sc
    host: smtp.gmail.com
    port: 587
    sender: adrian@apetre.sc

