version: "3.7"

services:
  bitwarden:
    image: vaultwarden/server:1.32.4
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.bitwarden.rule: "Host(`bitwarden.apetre.sc`)"
        traefik.http.routers.bitwarden.tls.certResolver: "r53resolver"
        traefik.http.routers.bitwarden.tls.domains[0].main: "apetre.sc"
        traefik.http.routers.bitwarden.tls.domains[0].sans: "*.apetre.sc"
        traefik.http.services.bitwarden.loadbalancer.server.port: 80
        traefik.docker.network: proxy
      placement:
        constraints:
          - node.labels.zpool == tank2
    secrets:
      - apetresc_smtp_password
      - bitwarden_admin_token
    environment:
      - DOMAIN=https://bitwarden.apetre.sc
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN_FILE=/run/secrets/bitwarden_admin_token
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=adrian@apetre.sc
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=adrian@apetre.sc
      - SMTP_PASSWORD_FILE=/run/secrets/apetresc_smtp_password
    volumes:
      - type: volume
        source: data
        target: /data
    networks:
      - proxy
    healthcheck:
      disable: false


volumes:
  data:
    driver: zfs

networks:
  proxy:
    external: true

secrets:
  apetresc_smtp_password:
    external: true
  bitwarden_admin_token:
    external: true
