version: '3.7'

services:
  reverse_proxy:
    image: traefik:v2.9.10
    deploy:
      placement:
        constraints:
          - node.hostname == red
    networks:
      - proxy
      - observe
    secrets:
      - route53_aws_credentials
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/route53_aws_credentials
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 2222
        published: 2222
        protocol: tcp
        mode: host
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    configs:
      - source: traefik_20230105f
        target: /etc/traefik/traefik.yaml
      - source: extra_services_20240215
        target: /etc/traefik/extra_services.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/traefik/certs

networks:
  proxy:
    external: true
  observe:
    external: true

volumes:
  certs:
    driver: zfs

configs:
  traefik_20230105f:
    file: ./config/traefik.yaml
  extra_services_20240215:
    file: ./config/extra_services.yaml

secrets:
  route53_aws_credentials:
    external: true
