global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets:
        - 'euclid:9100'
        - 'pythagoras:9100'
        - 'archimedes:9100'
        - 'red.local:9100'
  - job_name: traefik
    static_configs:
      - targets:
        - 'reverse_proxy:8082'
  - job_name: synapse
    metrics_path: '/_synapse/metrics'

    static_configs:
      - targets: ['synapse:9092']

