---
- hosts: archimedes
  pre_tasks:
    - name: Create NFS root
      ansible.builtin.file:
        path: /srv/nfs
        state: directory
    - name: Bind mount freezer
      ansible.posix.mount:
        path: /srv/nfs/freezer
        src: /data/freezer
        opts: bind
        state: mounted
        fstype: none
    - name: Bind mount unorted
      ansible.posix.mount:
        path: /srv/nfs/unsorted
        src: /data/unsorted
        opts: bind
        state: mounted
        fstype: none
  roles:
    - role: geerlingguy.nfs
  post_tasks:
    - name: enable rpc-statd
      ansible.builtin.systemd:
        name: rpc-statd
        daemon_reload: yes
        state: started
        enabled: yes

- hosts: smb
  pre_tasks:
    - name: Create SMB root
      ansible.builtin.file:
        path: /srv/smb
        state: directory
    - name: Bind mount freezer
      ansible.posix.mount:
        path: /srv/smb/freezer
        src: /data/freezer
        opts: bind
        state: mounted
        fstype: none
    - name: Bind mount unsorted
      ansible.posix.mount:
        path: /srv/smb/unsorted
        src: /data/unsorted
        opts: bind
        state: mounted
        fstype: none

  vars:
    samba_users:
      - name: apetresc
        password: "{{ apetresc_password }}"
      - name: jelee
        password: "{{ jelee_password }}"
    samba_shares_root: /srv/smb
    samba_shares:
      - name: freezer
        public: no
        valid_users: apetresc,jelee
        group: apetresc
        write_list: apetresc,jelee
      - name: unsorted
        public: no
        valid_users: apetresc
        write_list: apetresc
        group: apetresc
  roles:
    - role: bertvv.samba
    - role: wsdd
